### PR TITLE
Fabric samples byfn eyfn explained

### PR DESCRIPTION
**Pull request by ravinayag**

### CODE REVIEW

**Comment by nathalie-ckc** [comment]
Hi Ravi,

Sorry for the delay in getting my CONTRIBUTING.md update done.  Please refer to https://github.com/hyperledger/learning-materials-dev/blob/master/CONTRIBUTING.md for instructions on how to contribute a new project.

Regarding your specific Pull Request:
1) You've asked for FabricSamples to go directly in the top level directory.  It needs to go under ACTIVE/
2) To align with what we agreed made sense in the README.md, you need to create and populate the supporting files for the project with the relevant info (README.md, CONTRIBUTING.md, MAINTAINERS.md, TESTING.md)

Thanks & regards,
Nathalie

**Comment by ravinayag** [comment]
Updated with files and minor correction in Readme

**Comment by nathalie-ckc** [comment]
Hi Ravi, 
The DCO check failed.  Please see the details in the DCO check message for instructions on how to fix it. 
image

**Comment by nathalie-ckc** [comment]
Hi Ravi, while some of your commits are now passing DCO check, it reports:

"You have 7 commits incorrectly signed off. To fix, head to your local branch and run:

git rebase HEAD~28 --signoff
Now your commits will have your sign off. Next run

git push --force-with-lease origin fabric-samples-BYFN-EYFN-explained
Commit sha: a6fad2d, Author: ravinayag, Committer: GitHub; The sign-off is missing.
Commit sha: eece745, Author: ravinayag, Committer: GitHub; The sign-off is missing.
Commit sha: 4323f78, Author: ravinayag, Committer: GitHub; The sign-off is missing.
Commit sha: 147d23e, Author: Ravinayag, Committer: Ravinayag; The sign-off is missing.
Commit sha: 707f1f6, Author: Ravinayag, Committer: Ravinayag; The sign-off is missing.
Commit sha: 4d21f21, Author: Ravinayag, Committer: Ravinayag; The sign-off is missing.
Commit sha: d9d1b14, Author: ravinayag, Committer: GitHub; The sign-off is missing."

**Comment by ravinayag** [comment]
i did a new PR.

**Comment by ravinayag** [comment]
Hi Nathalie,

I raised a New PR, and closed old ones.

Hope this time cleared all DCO's

Thanks

**Pull request closed without merging**
